#ifndef TIMEZONE_H_
 #define TIMEZONE_H_




 #include <time.h>

 #define CONVTIME( x , y , z) ( ( x*3600 )+ ( y*60 ) + ( z ) )
  
 #define LEAP_YEAR(Y) ( ((1970+Y)>0) && !((1970+Y)%4) && ( ((1970+Y)%100) || !((1970+Y)%400) ) )
 #define SECS_PER_MIN  (60)
 #define SECS_PER_HOUR (3600)
 #define SECS_PER_DAY  (SECS_PER_HOUR * 24)
 #define weekday(t) (((t / SECS_PER_DAY) + 4) % 7)




/* needs to go to flash */
const timezone_t ZoneTable[TIMEZONEENUM_CNT] PROGMEM  ={
[Africa_Abidjan]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Accra]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Addis_Ababa]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Algiers]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Asmera]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Bamako]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Bangui]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Banjul]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Bissau]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Blantyre]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Brazzaville]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Bujumbura]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Cairo]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Fri , Apr , 00 , 00 , 3600 }, .EndRule={ Last , Fri , Sep , 00,00,0}},
[Africa_Casablanca]={.Zone=WET, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Ceuta]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Africa_Conakry]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Dakar]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Dar_es_Salaam]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Djibouti]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Douala]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_El_Aaiun]={.Zone=WET, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Freetown]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Gaborone]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Harare]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Johannesburg]={.Zone=SAST, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Kampala]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Khartoum]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Kigali]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Kinshasa]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Lagos]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Libreville]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Lome]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Luanda]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Lubumbashi]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Lusaka]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Malabo]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Maputo]={.Zone=CAT, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Maseru]={.Zone=SAST, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Mbabane]={.Zone=SAST, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Mogadishu]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Monrovia]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Nairobi]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Ndjamena]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Niamey]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Nouakchott]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Ouagadougou]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Porto_Novo]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Sao_Tome]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Timbuktu]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Tripoli]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Tunis]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Africa_Windhoek]={.Zone=WAT, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ First , Sun , Sep , 02 , 00 , 3600 }, .EndRule={ First , Sun , Apr , 02,00,0}},
[America_Adak]={.Zone=HAST, .Offset = CONVTIME(-10,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Anchorage]={.Zone=AKST, .Offset = CONVTIME(-9,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Anguilla]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Antigua]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Araguaina]={.Zone=BRT, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Third , Sun , Feb , 00,00,0}},
[America_Aruba]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Asuncion]={.Zone=PYT, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ First , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ First , Sun , Mar , 00,00,0}},
[America_Barbados]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Belem]={.Zone=BRT, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Belize]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Boa_Vista]={.Zone=AMT, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Bogota]={.Zone=COT, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Boise]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Buenos_Aires]={.Zone=ART, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Cambridge_Bay]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Cancun]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ First , Sun , May , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Sep , 02,00,0}},
[America_Caracas]={.Zone=VET, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Catamarca]={.Zone=ART, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Cayenne]={.Zone=GFT, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Cayman]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Chicago]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Chihuahua]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ First , Sun , May , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Sep , 02,00,0}},
[America_Cordoba]={.Zone=ART, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Costa_Rica]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Cuiaba]={.Zone=AMT, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Third , Sun , Feb , 00,00,0}},
[America_Curacao]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Danmarkshavn]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Dawson]={.Zone=PST, .Offset = CONVTIME(-8,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Dawson_Creek]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Denver]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Detroit]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Dominica]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Edmonton]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Eirunepe]={.Zone=ACT, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_El_Salvador]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Fortaleza]={.Zone=BRT, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Third , Sun , Feb , 00,00,0}},
[America_Glace_Bay]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Godthab]={.Zone=WGT, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Last , Sat , Mar , 22 , 00 , 3600 }, .EndRule={ Last , Sat , Oct , 23,00,0}},
[America_Goose_Bay]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 00 , 01 , 3600 }, .EndRule={ Last , Sun , Oct , 00,01,0}},
[America_Grand_Turk]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 00,00,0}},
[America_Grenada]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Guadeloupe]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Guatemala]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Guayaquil]={.Zone=ECT, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Guyana]={.Zone=GYT, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Halifax]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Havana]={.Zone=CST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 01,00,0}},
[America_Hermosillo]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Indiana_Indianapolis]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Indiana_Knox]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Indiana_Marengo]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Indiana_Vevay]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Indianapolis]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Inuvik]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Iqaluit]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Jamaica]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Jujuy]={.Zone=ART, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Juneau]={.Zone=AKST, .Offset = CONVTIME(-9,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Kentucky_Louisville]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Kentucky_Monticello]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_La_Paz]={.Zone=BOT, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Lima]={.Zone=PET, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Los_Angeles]={.Zone=PST, .Offset = CONVTIME(-8,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Louisville]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Maceio]={.Zone=BRT, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Third , Sun , Feb , 00,00,0}},
[America_Managua]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Manaus]={.Zone=AMT, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Martinique]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Mazatlan]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ First , Sun , May , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Sep , 02,00,0}},
[America_Mendoza]={.Zone=ART, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Menominee]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Merida]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ First , Sun , May , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Sep , 02,00,0}},
[America_Mexico_City]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Miquelon]={.Zone=PMST, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Monterrey]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ First , Sun , May , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Sep , 02,00,0}},
[America_Montevideo]={.Zone=UYT, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Montreal]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Montserrat]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Nassau]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[America_New_York]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Nipigon]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Nome]={.Zone=AKST, .Offset = CONVTIME(-9,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Noronha]={.Zone=FNT, .Offset = CONVTIME(-2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_North_Dakota_Center]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Panama]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Pangnirtung]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Paramaribo]={.Zone=SRT, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Phoenix]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Port_au_Prince]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Port_of_Spain]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Porto_Velho]={.Zone=AMT, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Puerto_Rico]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Rainy_River]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Rankin_Inlet]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Recife]={.Zone=BRT, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Third , Sun , Feb , 00,00,0}},
[America_Regina]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Rio_Branco]={.Zone=ACT, .Offset = CONVTIME(-5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Rosario]={.Zone=ART, .Offset = CONVTIME(-3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Santiago]={.Zone=CLT, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Second , Sun , Mar , 00,00,0}},
[America_Santo_Domingo]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Sao_Paulo]={.Zone=BRT, .Offset = CONVTIME(-3,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Third , Sun , Feb , 00,00,0}},
[America_Scoresbysund]={.Zone=EGT, .Offset = CONVTIME(-1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 01,00,0}},
[America_Shiprock]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_St_Johns]={.Zone=NST, .Offset = CONVTIME(-3,30,0), .has_dls=true, .StartRule={ First , Sun , Apr , 00 , 01 , 3600 }, .EndRule={ Last , Sun , Oct , 00,01,0}},
[America_St_Kitts]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_St_Lucia]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_St_Thomas]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_St_Vincent]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Swift_Current]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Tegucigalpa]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Thule]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Thunder_Bay]={.Zone=EST, .Offset = CONVTIME(-5,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Tijuana]={.Zone=PST, .Offset = CONVTIME(-8,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[America_Tortola]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[America_Vancouver]={.Zone=PST, .Offset = CONVTIME(-8,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Whitehorse]={.Zone=PST, .Offset = CONVTIME(-8,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Winnipeg]={.Zone=CST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 03,00,0}},
[America_Yakutat]={.Zone=AKST, .Offset = CONVTIME(-9,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[America_Yellowknife]={.Zone=MST, .Offset = CONVTIME(-7,0,0), .has_dls=true, .StartRule={ Second , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ First , Sun , Nov , 02,00,0}},
[Antarctica_Casey]={.Zone=WST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Antarctica_Davis]={.Zone=DAVT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Antarctica_DumontDUrville]={.Zone=DDUT, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Antarctica_Mawson]={.Zone=MAWT, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Antarctica_McMurdo]={.Zone=NZST, .Offset = CONVTIME(12,0,0), .has_dls=true, .StartRule={ First , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Third , Sun , Mar , 03,00,0}},
[Antarctica_Palmer]={.Zone=CLT, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ Second , Sun , Oct , 00 , 00 , 3600 }, .EndRule={ Second , Sun , Mar , 00,00,0}},
[Antarctica_South_Pole]={.Zone=NZST, .Offset = CONVTIME(12,0,0), .has_dls=true, .StartRule={ First , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Third , Sun , Mar , 03,00,0}},
[Antarctica_Syowa]={.Zone=SYOT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Antarctica_Vostok]={.Zone=VOST, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Arctic_Longyearbyen]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Aden]={.Zone=AST, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Almaty]={.Zone=ALMT, .Offset = CONVTIME(6,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 00,00,0}},
[Asia_Amman]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Thu , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Thu , Sep , 01,00,0}},
[Asia_Anadyr]={.Zone=ANAT, .Offset = CONVTIME(12,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Aqtau]={.Zone=AQTT, .Offset = CONVTIME(4,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 00,00,0}},
[Asia_Aqtobe]={.Zone=AQTT, .Offset = CONVTIME(5,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 00,00,0}},
[Asia_Ashgabat]={.Zone=TMT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Baghdad]={.Zone=AST, .Offset = CONVTIME(3,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 03 , 00 , 3600 }, .EndRule={ First , Sun , Oct , 04,00,0}},
[Asia_Bahrain]={.Zone=AST, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Baku]={.Zone=AZT, .Offset = CONVTIME(4,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 01,00,0}},
[Asia_Bangkok]={.Zone=ICT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Beirut]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 00,00,0}},
[Asia_Bishkek]={.Zone=KGT, .Offset = CONVTIME(5,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 30 , 3600 }, .EndRule={ Last , Sun , Oct , 02,30,0}},
[Asia_Brunei]={.Zone=BNT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Calcutta]={.Zone=IST, .Offset = CONVTIME(5,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Choibalsan]={.Zone=CHOT, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Chongqing]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Colombo]={.Zone=LKT, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Damascus]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 00 , 00 , 3600 }, .EndRule={ First , Sun , Oct , 00,00,0}},
[Asia_Dhaka]={.Zone=BDT, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Dili]={.Zone=TPT, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Dubai]={.Zone=GST, .Offset = CONVTIME(4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Dushanbe]={.Zone=TJT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Gaza]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Third , Fri , Apr , 00 , 00 , 3600 }, .EndRule={ Third , Fri , Oct , 00,00,0}},
[Asia_Harbin]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Hong_Kong]={.Zone=HKT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Hovd]={.Zone=HOVT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Irkutsk]={.Zone=IRKT, .Offset = CONVTIME(8,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Istanbul]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Asia_Jakarta]={.Zone=WIT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Jayapura]={.Zone=EIT, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Jerusalem]={.Zone=IST, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 01 , 00 , 3600 }, .EndRule={ First , Sun , Oct , 01,00,0}},
[Asia_Kabul]={.Zone=AFT, .Offset = CONVTIME(4,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Kamchatka]={.Zone=PETT, .Offset = CONVTIME(12,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Karachi]={.Zone=PKT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Kashgar]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Katmandu]={.Zone=NPT, .Offset = CONVTIME(5,45,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Krasnoyarsk]={.Zone=KRAT, .Offset = CONVTIME(7,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Kuala_Lumpur]={.Zone=MYT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Kuching]={.Zone=MYT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Kuwait]={.Zone=AST, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Macao]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Macau]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Magadan]={.Zone=MAGT, .Offset = CONVTIME(11,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Makassar]={.Zone=CIT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Manila]={.Zone=PHT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Muscat]={.Zone=GST, .Offset = CONVTIME(4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Nicosia]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Asia_Novosibirsk]={.Zone=NOVT, .Offset = CONVTIME(6,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Omsk]={.Zone=OMST, .Offset = CONVTIME(6,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Oral]={.Zone=WST, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Phnom_Penh]={.Zone=ICT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Pontianak]={.Zone=WIT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Pyongyang]={.Zone=KST, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Qyzylorda]={.Zone=KST, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Qatar]={.Zone=AST, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Rangoon]={.Zone=MMT, .Offset = CONVTIME(6,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Riyadh]={.Zone=AST, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Saigon]={.Zone=ICT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Sakhalin]={.Zone=SAKT, .Offset = CONVTIME(10,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Samarkand]={.Zone=UZT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Seoul]={.Zone=KST, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Shanghai]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Singapore]={.Zone=SGT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Taipei]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Tashkent]={.Zone=UZT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Tbilisi]={.Zone=GET, .Offset = CONVTIME(4,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 00,00,0}},
[Asia_Tehran]={.Zone=IRT, .Offset = CONVTIME(3,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Thimphu]={.Zone=BTT, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Tokyo]={.Zone=JST, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Ujung_Pandang]={.Zone=CIT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Ulaanbaatar]={.Zone=ULAT, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Urumqi]={.Zone=CST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Vientiane]={.Zone=ICT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Asia_Vladivostok]={.Zone=VLAT, .Offset = CONVTIME(10,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Yakutsk]={.Zone=YAKT, .Offset = CONVTIME(9,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Yekaterinburg]={.Zone=YEKT, .Offset = CONVTIME(5,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Asia_Yerevan]={.Zone=AMT, .Offset = CONVTIME(4,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Atlantic_Azores]={.Zone=AZOT, .Offset = CONVTIME(-1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 00 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 01,00,0}},
[Atlantic_Bermuda]={.Zone=AST, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ First , Sun , Apr , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Atlantic_Canary]={.Zone=WET, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Atlantic_Cape_Verde]={.Zone=CVT, .Offset = CONVTIME(-1,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Atlantic_Faeroe]={.Zone=WET, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Atlantic_Jan_Mayen]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Atlantic_Madeira]={.Zone=WET, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Atlantic_Reykjavik]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Atlantic_South_Georgia]={.Zone=GST, .Offset = CONVTIME(-2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Atlantic_St_Helena]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Atlantic_Stanley]={.Zone=FKT, .Offset = CONVTIME(-4,0,0), .has_dls=true, .StartRule={ First , Sun , Sep , 02 , 00 , 3600 }, .EndRule={ Third , Sun , Apr , 02,00,0}},
[Australia_Adelaide]={.Zone=CST, .Offset = CONVTIME(9,30,0), .has_dls=true, .StartRule={ Last , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Mar , 03,00,0}},
[Australia_Brisbane]={.Zone=EST, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Australia_Broken_Hill]={.Zone=CST, .Offset = CONVTIME(9,30,0), .has_dls=true, .StartRule={ Last , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Mar , 03,00,0}},
[Australia_Darwin]={.Zone=CST, .Offset = CONVTIME(9,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Australia_Hobart]={.Zone=EST, .Offset = CONVTIME(10,0,0), .has_dls=true, .StartRule={ First , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Mar , 03,00,0}},
[Australia_Lindeman]={.Zone=EST, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Australia_Lord_Howe]={.Zone=LHST, .Offset = CONVTIME(10,30,0), .has_dls=true, .StartRule={ Last , Sun , Oct , 02 , 00 , 1800 }, .EndRule={ Last , Sun , Mar , 02,00,0}},
[Australia_Melbourne]={.Zone=EST, .Offset = CONVTIME(10,0,0), .has_dls=true, .StartRule={ Last , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Mar , 03,00,0}},
[Australia_Perth]={.Zone=WST, .Offset = CONVTIME(8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Australia_Sydney]={.Zone=EST, .Offset = CONVTIME(10,0,0), .has_dls=true, .StartRule={ Last , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Mar , 03,00,0}},
[Europe_Amsterdam]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Andorra]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Athens]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Belfast]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Europe_Belgrade]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Berlin]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Bratislava]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Brussels]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Bucharest]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Budapest]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Chisinau]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Copenhagen]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Dublin]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Europe_Gibraltar]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Helsinki]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Istanbul]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Kaliningrad]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Kiev]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Lisbon]={.Zone=WET, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Europe_Ljubljana]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_London]={.Zone=GMT, .Offset = CONVTIME(0,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 01 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 02,00,0}},
[Europe_Luxembourg]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Madrid]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Malta]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Minsk]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Monaco]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Moscow]={.Zone=MSK, .Offset = CONVTIME(3,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Nicosia]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Oslo]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Paris]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Prague]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Riga]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Rome]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Samara]={.Zone=SAMT, .Offset = CONVTIME(4,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_San_Marino]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Sarajevo]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Simferopol]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Skopje]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Sofia]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Stockholm]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Tallinn]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Europe_Tirane]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Uzhgorod]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Vaduz]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Vatican]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Vienna]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Vilnius]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Europe_Warsaw]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Zagreb]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Europe_Zaporozhye]={.Zone=EET, .Offset = CONVTIME(2,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 03 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 04,00,0}},
[Europe_Zurich]={.Zone=CET, .Offset = CONVTIME(1,0,0), .has_dls=true, .StartRule={ Last , Sun , Mar , 02 , 00 , 3600 }, .EndRule={ Last , Sun , Oct , 03,00,0}},
[Indian_Antananarivo]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Chagos]={.Zone=IOT, .Offset = CONVTIME(6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Christmas]={.Zone=CXT, .Offset = CONVTIME(7,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Cocos]={.Zone=CCT, .Offset = CONVTIME(6,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Comoro]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Kerguelen]={.Zone=TFT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Mahe]={.Zone=SCT, .Offset = CONVTIME(4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Maldives]={.Zone=MVT, .Offset = CONVTIME(5,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Mauritius]={.Zone=MUT, .Offset = CONVTIME(4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Mayotte]={.Zone=EAT, .Offset = CONVTIME(3,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Indian_Reunion]={.Zone=RET, .Offset = CONVTIME(4,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Apia]={.Zone=WST, .Offset = CONVTIME(-11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Auckland]={.Zone=NZST, .Offset = CONVTIME(12,0,0), .has_dls=true, .StartRule={ First , Sun , Oct , 02 , 00 , 3600 }, .EndRule={ Third , Sun , Mar , 03,00,0}},
[Pacific_Chatham]={.Zone=CHAST, .Offset = CONVTIME(12,45,0), .has_dls=true, .StartRule={ First , Sun , Oct , 02 , 45 , 3600 }, .EndRule={ Third , Sun , Mar , 03,45,0}},
[Pacific_Easter]={.Zone=EAST, .Offset = CONVTIME(-6,0,0), .has_dls=true, .StartRule={ Second , Sat , Oct , 22 , 00 , 3600 }, .EndRule={ Second , Sat , Mar , 22,00,0}},
[Pacific_Efate]={.Zone=VUT, .Offset = CONVTIME(11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Enderbury]={.Zone=PHOT, .Offset = CONVTIME(13,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Fakaofo]={.Zone=TKT, .Offset = CONVTIME(-10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Fiji]={.Zone=FJT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Funafuti]={.Zone=TVT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Galapagos]={.Zone=GALT, .Offset = CONVTIME(-6,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Gambier]={.Zone=GAMT, .Offset = CONVTIME(-9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Guadalcanal]={.Zone=SBT, .Offset = CONVTIME(11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Guam]={.Zone=ChST, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Honolulu]={.Zone=HST, .Offset = CONVTIME(-10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Johnston]={.Zone=HST, .Offset = CONVTIME(-10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Kiritimati]={.Zone=LINT, .Offset = CONVTIME(14,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Kosrae]={.Zone=KOST, .Offset = CONVTIME(11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Kwajalein]={.Zone=MHT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Majuro]={.Zone=MHT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Marquesas]={.Zone=MART, .Offset = CONVTIME(-9,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Midway]={.Zone=SST, .Offset = CONVTIME(-11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Nauru]={.Zone=NRT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Niue]={.Zone=NUT, .Offset = CONVTIME(-11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Norfolk]={.Zone=NFT, .Offset = CONVTIME(11,30,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Noumea]={.Zone=NCT, .Offset = CONVTIME(11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Pago_Pago]={.Zone=SST, .Offset = CONVTIME(-11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Palau]={.Zone=PWT, .Offset = CONVTIME(9,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Pitcairn]={.Zone=PST, .Offset = CONVTIME(-8,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Ponape]={.Zone=PONT, .Offset = CONVTIME(11,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Port_Moresby]={.Zone=PGT, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Rarotonga]={.Zone=CKT, .Offset = CONVTIME(-10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Saipan]={.Zone=ChST, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Tahiti]={.Zone=TAHT, .Offset = CONVTIME(-10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Tarawa]={.Zone=GILT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Tongatapu]={.Zone=TOT, .Offset = CONVTIME(13,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Truk]={.Zone=TRUT, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Wake]={.Zone=WAKT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Wallis]={.Zone=WFT, .Offset = CONVTIME(12,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}},
[Pacific_Yap]={.Zone=YAPT, .Offset = CONVTIME(10,0,0), .has_dls=false, .StartRule={ First, Sun, Jan, 0, 0}, .EndRule={ First, Sun, Jan, 0, 0,0}}
};

/* needs to go to flash */
/*
const char* TimeZoneNames[TIMEZONEENUM_CNT] ={
[Africa_Abidjan]="Africa/Abidjan",
[Africa_Accra]="Africa/Accra",
[Africa_Addis_Ababa]="Africa/Addis_Ababa",
[Africa_Algiers]="Africa/Algiers",
[Africa_Asmera]="Africa/Asmera",
[Africa_Bamako]="Africa/Bamako",
[Africa_Bangui]="Africa/Bangui",
[Africa_Banjul]="Africa/Banjul",
[Africa_Bissau]="Africa/Bissau",
[Africa_Blantyre]="Africa/Blantyre",
[Africa_Brazzaville]="Africa/Brazzaville",
[Africa_Bujumbura]="Africa/Bujumbura",
[Africa_Cairo]="Africa/Cairo",
[Africa_Casablanca]="Africa/Casablanca",
[Africa_Ceuta]="Africa/Ceuta",
[Africa_Conakry]="Africa/Conakry",
[Africa_Dakar]="Africa/Dakar",
[Africa_Dar_es_Salaam]="Africa/Dar_es_Salaam",
[Africa_Djibouti]="Africa/Djibouti",
[Africa_Douala]="Africa/Douala",
[Africa_El_Aaiun]="Africa/El_Aaiun",
[Africa_Freetown]="Africa/Freetown",
[Africa_Gaborone]="Africa/Gaborone",
[Africa_Harare]="Africa/Harare",
[Africa_Johannesburg]="Africa/Johannesburg",
[Africa_Kampala]="Africa/Kampala",
[Africa_Khartoum]="Africa/Khartoum",
[Africa_Kigali]="Africa/Kigali",
[Africa_Kinshasa]="Africa/Kinshasa",
[Africa_Lagos]="Africa/Lagos",
[Africa_Libreville]="Africa/Libreville",
[Africa_Lome]="Africa/Lome",
[Africa_Luanda]="Africa/Luanda",
[Africa_Lubumbashi]="Africa/Lubumbashi",
[Africa_Lusaka]="Africa/Lusaka",
[Africa_Malabo]="Africa/Malabo",
[Africa_Maputo]="Africa/Maputo",
[Africa_Maseru]="Africa/Maseru",
[Africa_Mbabane]="Africa/Mbabane",
[Africa_Mogadishu]="Africa/Mogadishu",
[Africa_Monrovia]="Africa/Monrovia",
[Africa_Nairobi]="Africa/Nairobi",
[Africa_Ndjamena]="Africa/Ndjamena",
[Africa_Niamey]="Africa/Niamey",
[Africa_Nouakchott]="Africa/Nouakchott",
[Africa_Ouagadougou]="Africa/Ouagadougou",
[Africa_Porto_Novo]="Africa/Porto-Novo",
[Africa_Sao_Tome]="Africa/Sao_Tome",
[Africa_Timbuktu]="Africa/Timbuktu",
[Africa_Tripoli]="Africa/Tripoli",
[Africa_Tunis]="Africa/Tunis",
[Africa_Windhoek]="Africa/Windhoek",
[America_Adak]="America/Adak",
[America_Anchorage]="America/Anchorage",
[America_Anguilla]="America/Anguilla",
[America_Antigua]="America/Antigua",
[America_Araguaina]="America/Araguaina",
[America_Aruba]="America/Aruba",
[America_Asuncion]="America/Asuncion",
[America_Barbados]="America/Barbados",
[America_Belem]="America/Belem",
[America_Belize]="America/Belize",
[America_Boa_Vista]="America/Boa_Vista",
[America_Bogota]="America/Bogota",
[America_Boise]="America/Boise",
[America_Buenos_Aires]="America/Buenos_Aires",
[America_Cambridge_Bay]="America/Cambridge_Bay",
[America_Cancun]="America/Cancun",
[America_Caracas]="America/Caracas",
[America_Catamarca]="America/Catamarca",
[America_Cayenne]="America/Cayenne",
[America_Cayman]="America/Cayman",
[America_Chicago]="America/Chicago",
[America_Chihuahua]="America/Chihuahua",
[America_Cordoba]="America/Cordoba",
[America_Costa_Rica]="America/Costa_Rica",
[America_Cuiaba]="America/Cuiaba",
[America_Curacao]="America/Curacao",
[America_Danmarkshavn]="America/Danmarkshavn",
[America_Dawson]="America/Dawson",
[America_Dawson_Creek]="America/Dawson_Creek",
[America_Denver]="America/Denver",
[America_Detroit]="America/Detroit",
[America_Dominica]="America/Dominica",
[America_Edmonton]="America/Edmonton",
[America_Eirunepe]="America/Eirunepe",
[America_El_Salvador]="America/El_Salvador",
[America_Fortaleza]="America/Fortaleza",
[America_Glace_Bay]="America/Glace_Bay",
[America_Godthab]="America/Godthab",
[America_Goose_Bay]="America/Goose_Bay",
[America_Grand_Turk]="America/Grand_Turk",
[America_Grenada]="America/Grenada",
[America_Guadeloupe]="America/Guadeloupe",
[America_Guatemala]="America/Guatemala",
[America_Guayaquil]="America/Guayaquil",
[America_Guyana]="America/Guyana",
[America_Halifax]="America/Halifax",
[America_Havana]="America/Havana",
[America_Hermosillo]="America/Hermosillo",
[America_Indiana_Indianapolis]="America/Indiana/Indianapolis",
[America_Indiana_Knox]="America/Indiana/Knox",
[America_Indiana_Marengo]="America/Indiana/Marengo",
[America_Indiana_Vevay]="America/Indiana/Vevay",
[America_Indianapolis]="America/Indianapolis",
[America_Inuvik]="America/Inuvik",
[America_Iqaluit]="America/Iqaluit",
[America_Jamaica]="America/Jamaica",
[America_Jujuy]="America/Jujuy",
[America_Juneau]="America/Juneau",
[America_Kentucky_Louisville]="America/Kentucky/Louisville",
[America_Kentucky_Monticello]="America/Kentucky/Monticello",
[America_La_Paz]="America/La_Paz",
[America_Lima]="America/Lima",
[America_Los_Angeles]="America/Los_Angeles",
[America_Louisville]="America/Louisville",
[America_Maceio]="America/Maceio",
[America_Managua]="America/Managua",
[America_Manaus]="America/Manaus",
[America_Martinique]="America/Martinique",
[America_Mazatlan]="America/Mazatlan",
[America_Mendoza]="America/Mendoza",
[America_Menominee]="America/Menominee",
[America_Merida]="America/Merida",
[America_Mexico_City]="America/Mexico_City",
[America_Miquelon]="America/Miquelon",
[America_Monterrey]="America/Monterrey",
[America_Montevideo]="America/Montevideo",
[America_Montreal]="America/Montreal",
[America_Montserrat]="America/Montserrat",
[America_Nassau]="America/Nassau",
[America_New_York]="America/New_York",
[America_Nipigon]="America/Nipigon",
[America_Nome]="America/Nome",
[America_Noronha]="America/Noronha",
[America_North_Dakota_Center]="America/North_Dakota/Center",
[America_Panama]="America/Panama",
[America_Pangnirtung]="America/Pangnirtung",
[America_Paramaribo]="America/Paramaribo",
[America_Phoenix]="America/Phoenix",
[America_Port_au_Prince]="America/Port-au-Prince",
[America_Port_of_Spain]="America/Port_of_Spain",
[America_Porto_Velho]="America/Porto_Velho",
[America_Puerto_Rico]="America/Puerto_Rico",
[America_Rainy_River]="America/Rainy_River",
[America_Rankin_Inlet]="America/Rankin_Inlet",
[America_Recife]="America/Recife",
[America_Regina]="America/Regina",
[America_Rio_Branco]="America/Rio_Branco",
[America_Rosario]="America/Rosario",
[America_Santiago]="America/Santiago",
[America_Santo_Domingo]="America/Santo_Domingo",
[America_Sao_Paulo]="America/Sao_Paulo",
[America_Scoresbysund]="America/Scoresbysund",
[America_Shiprock]="America/Shiprock",
[America_St_Johns]="America/St_Johns",
[America_St_Kitts]="America/St_Kitts",
[America_St_Lucia]="America/St_Lucia",
[America_St_Thomas]="America/St_Thomas",
[America_St_Vincent]="America/St_Vincent",
[America_Swift_Current]="America/Swift_Current",
[America_Tegucigalpa]="America/Tegucigalpa",
[America_Thule]="America/Thule",
[America_Thunder_Bay]="America/Thunder_Bay",
[America_Tijuana]="America/Tijuana",
[America_Tortola]="America/Tortola",
[America_Vancouver]="America/Vancouver",
[America_Whitehorse]="America/Whitehorse",
[America_Winnipeg]="America/Winnipeg",
[America_Yakutat]="America/Yakutat",
[America_Yellowknife]="America/Yellowknife",
[Antarctica_Casey]="Antarctica/Casey",
[Antarctica_Davis]="Antarctica/Davis",
[Antarctica_DumontDUrville]="Antarctica/DumontDUrville",
[Antarctica_Mawson]="Antarctica/Mawson",
[Antarctica_McMurdo]="Antarctica/McMurdo",
[Antarctica_Palmer]="Antarctica/Palmer",
[Antarctica_South_Pole]="Antarctica/South_Pole",
[Antarctica_Syowa]="Antarctica/Syowa",
[Antarctica_Vostok]="Antarctica/Vostok",
[Arctic_Longyearbyen]="Arctic/Longyearbyen",
[Asia_Aden]="Asia/Aden",
[Asia_Almaty]="Asia/Almaty",
[Asia_Amman]="Asia/Amman",
[Asia_Anadyr]="Asia/Anadyr",
[Asia_Aqtau]="Asia/Aqtau",
[Asia_Aqtobe]="Asia/Aqtobe",
[Asia_Ashgabat]="Asia/Ashgabat",
[Asia_Baghdad]="Asia/Baghdad",
[Asia_Bahrain]="Asia/Bahrain",
[Asia_Baku]="Asia/Baku",
[Asia_Bangkok]="Asia/Bangkok",
[Asia_Beirut]="Asia/Beirut",
[Asia_Bishkek]="Asia/Bishkek",
[Asia_Brunei]="Asia/Brunei",
[Asia_Calcutta]="Asia/Calcutta",
[Asia_Choibalsan]="Asia/Choibalsan",
[Asia_Chongqing]="Asia/Chongqing",
[Asia_Colombo]="Asia/Colombo",
[Asia_Damascus]="Asia/Damascus",
[Asia_Dhaka]="Asia/Dhaka",
[Asia_Dili]="Asia/Dili",
[Asia_Dubai]="Asia/Dubai",
[Asia_Dushanbe]="Asia/Dushanbe",
[Asia_Gaza]="Asia/Gaza",
[Asia_Harbin]="Asia/Harbin",
[Asia_Hong_Kong]="Asia/Hong_Kong",
[Asia_Hovd]="Asia/Hovd",
[Asia_Irkutsk]="Asia/Irkutsk",
[Asia_Istanbul]="Asia/Istanbul",
[Asia_Jakarta]="Asia/Jakarta",
[Asia_Jayapura]="Asia/Jayapura",
[Asia_Jerusalem]="Asia/Jerusalem",
[Asia_Kabul]="Asia/Kabul",
[Asia_Kamchatka]="Asia/Kamchatka",
[Asia_Karachi]="Asia/Karachi",
[Asia_Kashgar]="Asia/Kashgar",
[Asia_Katmandu]="Asia/Katmandu",
[Asia_Krasnoyarsk]="Asia/Krasnoyarsk",
[Asia_Kuala_Lumpur]="Asia/Kuala_Lumpur",
[Asia_Kuching]="Asia/Kuching",
[Asia_Kuwait]="Asia/Kuwait",
[Asia_Macao]="Asia/Macao",
[Asia_Macau]="Asia/Macau",
[Asia_Magadan]="Asia/Magadan",
[Asia_Makassar]="Asia/Makassar",
[Asia_Manila]="Asia/Manila",
[Asia_Muscat]="Asia/Muscat",
[Asia_Nicosia]="Asia/Nicosia",
[Asia_Novosibirsk]="Asia/Novosibirsk",
[Asia_Omsk]="Asia/Omsk",
[Asia_Oral]="Asia/Oral",
[Asia_Phnom_Penh]="Asia/Phnom_Penh",
[Asia_Pontianak]="Asia/Pontianak",
[Asia_Pyongyang]="Asia/Pyongyang",
[Asia_Qyzylorda]="Asia/Qyzylorda",
[Asia_Qatar]="Asia/Qatar",
[Asia_Rangoon]="Asia/Rangoon",
[Asia_Riyadh]="Asia/Riyadh",
[Asia_Saigon]="Asia/Saigon",
[Asia_Sakhalin]="Asia/Sakhalin",
[Asia_Samarkand]="Asia/Samarkand",
[Asia_Seoul]="Asia/Seoul",
[Asia_Shanghai]="Asia/Shanghai",
[Asia_Singapore]="Asia/Singapore",
[Asia_Taipei]="Asia/Taipei",
[Asia_Tashkent]="Asia/Tashkent",
[Asia_Tbilisi]="Asia/Tbilisi",
[Asia_Tehran]="Asia/Tehran",
[Asia_Thimphu]="Asia/Thimphu",
[Asia_Tokyo]="Asia/Tokyo",
[Asia_Ujung_Pandang]="Asia/Ujung_Pandang",
[Asia_Ulaanbaatar]="Asia/Ulaanbaatar",
[Asia_Urumqi]="Asia/Urumqi",
[Asia_Vientiane]="Asia/Vientiane",
[Asia_Vladivostok]="Asia/Vladivostok",
[Asia_Yakutsk]="Asia/Yakutsk",
[Asia_Yekaterinburg]="Asia/Yekaterinburg",
[Asia_Yerevan]="Asia/Yerevan",
[Atlantic_Azores]="Atlantic/Azores",
[Atlantic_Bermuda]="Atlantic/Bermuda",
[Atlantic_Canary]="Atlantic/Canary",
[Atlantic_Cape_Verde]="Atlantic/Cape_Verde",
[Atlantic_Faeroe]="Atlantic/Faeroe",
[Atlantic_Jan_Mayen]="Atlantic/Jan_Mayen",
[Atlantic_Madeira]="Atlantic/Madeira",
[Atlantic_Reykjavik]="Atlantic/Reykjavik",
[Atlantic_South_Georgia]="Atlantic/South_Georgia",
[Atlantic_St_Helena]="Atlantic/St_Helena",
[Atlantic_Stanley]="Atlantic/Stanley",
[Australia_Adelaide]="Australia/Adelaide",
[Australia_Brisbane]="Australia/Brisbane",
[Australia_Broken_Hill]="Australia/Broken_Hill",
[Australia_Darwin]="Australia/Darwin",
[Australia_Hobart]="Australia/Hobart",
[Australia_Lindeman]="Australia/Lindeman",
[Australia_Lord_Howe]="Australia/Lord_Howe",
[Australia_Melbourne]="Australia/Melbourne",
[Australia_Perth]="Australia/Perth",
[Australia_Sydney]="Australia/Sydney",
[Europe_Amsterdam]="Europe/Amsterdam",
[Europe_Andorra]="Europe/Andorra",
[Europe_Athens]="Europe/Athens",
[Europe_Belfast]="Europe/Belfast",
[Europe_Belgrade]="Europe/Belgrade",
[Europe_Berlin]="Europe/Berlin",
[Europe_Bratislava]="Europe/Bratislava",
[Europe_Brussels]="Europe/Brussels",
[Europe_Bucharest]="Europe/Bucharest",
[Europe_Budapest]="Europe/Budapest",
[Europe_Chisinau]="Europe/Chisinau",
[Europe_Copenhagen]="Europe/Copenhagen",
[Europe_Dublin]="Europe/Dublin",
[Europe_Gibraltar]="Europe/Gibraltar",
[Europe_Helsinki]="Europe/Helsinki",
[Europe_Istanbul]="Europe/Istanbul",
[Europe_Kaliningrad]="Europe/Kaliningrad",
[Europe_Kiev]="Europe/Kiev",
[Europe_Lisbon]="Europe/Lisbon",
[Europe_Ljubljana]="Europe/Ljubljana",
[Europe_London]="Europe/London",
[Europe_Luxembourg]="Europe/Luxembourg",
[Europe_Madrid]="Europe/Madrid",
[Europe_Malta]="Europe/Malta",
[Europe_Minsk]="Europe/Minsk",
[Europe_Monaco]="Europe/Monaco",
[Europe_Moscow]="Europe/Moscow",
[Europe_Nicosia]="Europe/Nicosia",
[Europe_Oslo]="Europe/Oslo",
[Europe_Paris]="Europe/Paris",
[Europe_Prague]="Europe/Prague",
[Europe_Riga]="Europe/Riga",
[Europe_Rome]="Europe/Rome",
[Europe_Samara]="Europe/Samara",
[Europe_San_Marino]="Europe/San_Marino",
[Europe_Sarajevo]="Europe/Sarajevo",
[Europe_Simferopol]="Europe/Simferopol",
[Europe_Skopje]="Europe/Skopje",
[Europe_Sofia]="Europe/Sofia",
[Europe_Stockholm]="Europe/Stockholm",
[Europe_Tallinn]="Europe/Tallinn",
[Europe_Tirane]="Europe/Tirane",
[Europe_Uzhgorod]="Europe/Uzhgorod",
[Europe_Vaduz]="Europe/Vaduz",
[Europe_Vatican]="Europe/Vatican",
[Europe_Vienna]="Europe/Vienna",
[Europe_Vilnius]="Europe/Vilnius",
[Europe_Warsaw]="Europe/Warsaw",
[Europe_Zagreb]="Europe/Zagreb",
[Europe_Zaporozhye]="Europe/Zaporozhye",
[Europe_Zurich]="Europe/Zurich",
[Indian_Antananarivo]="Indian/Antananarivo",
[Indian_Chagos]="Indian/Chagos",
[Indian_Christmas]="Indian/Christmas",
[Indian_Cocos]="Indian/Cocos",
[Indian_Comoro]="Indian/Comoro",
[Indian_Kerguelen]="Indian/Kerguelen",
[Indian_Mahe]="Indian/Mahe",
[Indian_Maldives]="Indian/Maldives",
[Indian_Mauritius]="Indian/Mauritius",
[Indian_Mayotte]="Indian/Mayotte",
[Indian_Reunion]="Indian/Reunion",
[Pacific_Apia]="Pacific/Apia",
[Pacific_Auckland]="Pacific/Auckland",
[Pacific_Chatham]="Pacific/Chatham",
[Pacific_Easter]="Pacific/Easter",
[Pacific_Efate]="Pacific/Efate",
[Pacific_Enderbury]="Pacific/Enderbury",
[Pacific_Fakaofo]="Pacific/Fakaofo",
[Pacific_Fiji]="Pacific/Fiji",
[Pacific_Funafuti]="Pacific/Funafuti",
[Pacific_Galapagos]="Pacific/Galapagos",
[Pacific_Gambier]="Pacific/Gambier",
[Pacific_Guadalcanal]="Pacific/Guadalcanal",
[Pacific_Guam]="Pacific/Guam",
[Pacific_Honolulu]="Pacific/Honolulu",
[Pacific_Johnston]="Pacific/Johnston",
[Pacific_Kiritimati]="Pacific/Kiritimati",
[Pacific_Kosrae]="Pacific/Kosrae",
[Pacific_Kwajalein]="Pacific/Kwajalein",
[Pacific_Majuro]="Pacific/Majuro",
[Pacific_Marquesas]="Pacific/Marquesas",
[Pacific_Midway]="Pacific/Midway",
[Pacific_Nauru]="Pacific/Nauru",
[Pacific_Niue]="Pacific/Niue",
[Pacific_Norfolk]="Pacific/Norfolk",
[Pacific_Noumea]="Pacific/Noumea",
[Pacific_Pago_Pago]="Pacific/Pago_Pago",
[Pacific_Palau]="Pacific/Palau",
[Pacific_Pitcairn]="Pacific/Pitcairn",
[Pacific_Ponape]="Pacific/Ponape",
[Pacific_Port_Moresby]="Pacific/Port_Moresby",
[Pacific_Rarotonga]="Pacific/Rarotonga",
[Pacific_Saipan]="Pacific/Saipan",
[Pacific_Tahiti]="Pacific/Tahiti",
[Pacific_Tarawa]="Pacific/Tarawa",
[Pacific_Tongatapu]="Pacific/Tongatapu",
[Pacific_Truk]="Pacific/Truk",
[Pacific_Wake]="Pacific/Wake",
[Pacific_Wallis]="Pacific/Wallis",
[Pacific_Yap]="Pacific/Yap"

};
 */
#endif
